# setings
title: Suma sobre filosofía medieval
author: 
  name: Ivan Ortiz
  email: fernandoivan.ortizsantillan@gmail.com 
description: Trabajo acerca de la filosofía en la Edad Media
# tema / diseño
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
